Return null from I18nTags::languageObject if Language could not be determined
Causing logspam on twn:

TypeError: Return value of I18nTags::languageObject() must be an
instance of Language or null, none returned

Change-Id: I7ab7cdc441728766acfaa4a2e9906c86a072f176